### ISSUE TITLE
using @babel/plugin-transform-runtime without @babel/runtime

### ISSUE THREAD

**Issue by Y-k-Y** [hg-pyun/step-by-step-webpack-config#5]
@babel/runtime 없이 빌드하니 계속 오류가 나서 구글에 이 이슈로 검색을 해보니 
@babel/plugin-transform-runtime 을 사용할 때는 @babel/runtime 도 설치를 해야 한다고 해서 설치를 했는데 error는 없어졌는데 typeof를 찾을 수 없다는 경고가 사라지지가 않네요. 이 프로젝트에서는 @babel/runtime을 설치 안 하셨던데 정상적으로 잘 되나요??

**Comment by hg-pyun** [comment]
이전 바벨 버전에서는 `transform-runtime`을 설치하면 디펜던시로 `babel-runtime`이 설치되었는데, 바벨 7의 특정버전부터는 의존성이 분리되었다고 합니다.  현재는 `babel/runtime`을 같이 설치하는게 맞습니다!

**Comment by Y-k-Y** [comment]
빠른 답변 감사합니다!
